---
title: "HW 3"
author: "Ben Camber"
date: "1/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1:
Regex finds instances of two or more spaces, but not line breaks.

#### Find: 
``` 
\s{2,}

```
#### Replace:
```
,
```



## Problem 2:
Regex captures first name, last name, and all the rest. Order of names reversed and all the rest is put in parentheses.

#### Find:
```
(\w+), (\w+), (.*)
```
#### Replace:
```
\2 \1 (\3)
```


## Problem 3:
Regex finds all instances of .mp3 followed by a space, captures .mp3, and replaces the space with a new line.

#### Find:
```
(.mp3)\s
```
#### Replace:
```
\1\n
```


## Problem 4:
Regex captures numbers with 2 or more digits followed by a space, then captures everything before .mp3 as well as .mp3 so they can be replaced in a different order. 

#### Find:
```
(\d{2,}) (.*)(.mp3)
```

#### Replace:
```
\2_\1\3
```


## Problem 5:
Regex captures the first letter of the first word, the whole second word, and the last number with any number of digits and eliminates everything else. 

#### Find:
```
(\w)\w+,(\w+),\d+.\d,(\d+)
```
##### Replace:
```
\1_\2,\3
```


## Problem 6:
Regex captures the first letter of the first word, the first four letters of the second word, and the final comma and number, then eliminates everything else. 

#### Find:
```
(\w{1})\w*,(\w{4})\w*,\d*.\d(,\d*)
```
#### Replace:
```
\1_\2\3
```


## Problem 7:
Regex captures the first three letters of the first word, the first three letters of the second word, and the comma followed by everything else, then eliminates the leftovers. 

#### Find:
```
(\w{3})\w*,(\w{3})\w*(,.*)
```
#### Replace
```
\1\2\3
```
